aliyunSms:
  AccessKeyID: LTAI4FuYubZkypAjmCvocsyP
  AccessKeySecret: 5SeE9A47cW19M30ZlLL5T8mPIfWFHX
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.97.188.93:8761/eureka/
server:
  port: 8888
  servlet:
    context-path: /sms
spring:
  application:
    name: sms-server




