
#启动端口号
server:
  port: 8888
  servlet:
    context-path: /sms

#订单服务地址
spring:
  application:
    name: sms-server
---

#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.97.188.93:8761/eureka/



#==========================阿里云短信服务=======================
aliyunSms:
  AccessKeyID: LTAI4FuYubZkypAjmCvocsyP
  AccessKeySecret: 5SeE9A47cW19M30ZlLL5T8mPIfWFHX





